### ISSUE TITLE
Help! need support for TLS v1.3

### ISSUE THREAD

**Issue by houssam84** [wolfSSL/Arduino-wolfSSL#9]
hi, I have compiled project with TLS v1.2.  It is OK. but the following test results (undefined reference to `wolfTLSv1_3_server_method'):

#include <wolfssl.h>
#include <wolfssl/options.h>
#include <wolfssl/ssl.h>

void setup() {
  Serial.begin(115200);

  wolfSSL_Init();

  WOLFSSL_CTX* ctx = wolfSSL_CTX_new(**wolfTLSv1_3_server_method()**);
  if (ctx) {
    Serial.println("TLS 1.3 is supported and context created successfully!");
    wolfSSL_CTX_free(ctx);
  } else {
    Serial.println("Failed to initialize TLS 1.3 context.");
  }
}

void loop() {
  // Nothing to do here
}

**Comment by anhu** [comment]
Hi @houssam84 , 

Thanks for reaching out to us here at wolfSSL.  May I ask, how do you configure and build wolfSSL.  Do you use configure or do you have a user_settings.h ? In either case,  can you let us know what options you enable/disable? 

Here at wolfSSL, we love it when the community uses our code and we love to learn how they are using it.  Can you please let me know a bit about yourself and your project? What are you trying to achieve? Where are you geographically located? Is this question out of personal, academic or professional interest?  Are there any organizations associated with this work?  Any information is useful in helping us prioritize your request. 

Warm regards, Anthony

**Comment by houssam84** [comment]
Thank u for your response. i appreciate your support.
Regarding your questions:

* I havent configured wolfSSL using (cmake) yet. Should I configure and build wolfSSL using it?
* after your mention ,I read user_settings.h.  I enabled this option directly. 
#define WOLFSSL_TLS13
And it builds successfully. but not tested yet. Thank u
* is it sufficient? or i need to enable/disable more options.

* The goal of the project is to integrate secure communication using TLS v1.2/1.3. While the build for TLS v1.2 is successful, the issue occurs when I attempt to test for wolfTLSv1_3_server_method, resulting in the undefined reference error.

This work is part of an IOT exploring secure communication protocols and is not currently tied to an organization or specific personal interest. Any guidance you can provide to resolve the issue would be greatly appreciated.

Thank you for your support.

Best regards,

**Comment by anhu** [comment]
Hi,
To simplify things, I would simply use `./configure` That will keep it simple.  Please try that and let me know how it goes.
